name       : gedit-plugins
version    : '44.0'
release    : 34
source     :
    - https://download.gnome.org/sources/gedit-plugins/44/gedit-plugins-44.0.tar.xz : 1e9ee3a92582587d178611f6e0a4afbd14ac1b47209537f443796eb9710826b6
homepage   : https://gitlab.gnome.org/GNOME/gedit-plugins
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Gedit Plugins
description: |
    Gedit Plugins
builddeps  :
    - pkgconfig(gedit)
    - pkgconfig(gucharmap-2.90)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(vte-2.91)
    - appstream-glib
    - itstool
    - vala
rundeps    :
    - gucharmap
    - libgit2-glib
    - python-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
