name       : gedit-plugins
version    : 3.16.0
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gedit-plugins/3.16/gedit-plugins-3.16.0.tar.xz : b685b84ada8ca04f6aa201e402a0208591be4a37b874595a0a85d0a14b52f191
license    : GPL-2.0
summary    : Gedit Plugins
description: |
    Gedit Plugins
builddeps  :
    - pkgconfig(gedit)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
