name       : gedit-plugins
version    : 3.38.1
release    : 24
source     :
    - https://download.gnome.org/sources/gedit-plugins/3.38/gedit-plugins-3.38.1.tar.xz : 6c0fa314257f37f1b0151ed77ccfdc49ed61fa52f32ec1e802e4a6d0e6aee2bf
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Gedit Plugins
description: |
    Gedit Plugins
builddeps  :
    - pkgconfig(gedit)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(gucharmap-2.90)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(vte-2.91)
    - appstream-glib
    - itstool
    - vala
rundeps    :
    - libgit2-glib
    - python-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
