name       : gedit-plugins
version    : '42.1'
release    : 31
source     :
    - https://download.gnome.org/sources/gedit-plugins/42/gedit-plugins-42.1.tar.xz : c6b741de7d2610b0e474ef1b72a2a587e236998573403d527fe18e9e3de2623d
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Gedit Plugins
description: |
    Gedit Plugins
builddeps  :
    - pkgconfig(gedit)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(gucharmap-2.90)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(vte-2.91)
    - appstream-glib
    - itstool
    - vala
rundeps    :
    - gucharmap
    - libgit2-glib
    - python-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
