name       : gedit-plugins
version    : '43.1'
release    : 33
source     :
    - https://download.gnome.org/sources/gedit-plugins/43/gedit-plugins-43.1.tar.xz : 93a4ff0f60e8283293f16c242c25eb197e5e7bdc06cbe8891b82cf1d46cc6e1d
homepage   : https://gitlab.gnome.org/GNOME/gedit-plugins
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Gedit Plugins
description: |
    Gedit Plugins
builddeps  :
    - pkgconfig(gedit)
    - pkgconfig(gucharmap-2.90)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(vte-2.91)
    - appstream-glib
    - itstool
    - vala
rundeps    :
    - gucharmap
    - libgit2-glib
    - python-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
