name       : gedit-plugins
version    : 3.18.0
release    : 4
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gedit-plugins/3.18/gedit-plugins-3.18.0.tar.xz : e25249c0c2a057827bb4d4755a2359e1f9b4de288e0c4e201c6ef4f0e0e8c580
license    : GPL-2.0
summary    : Gedit Plugins
description: |
    Gedit Plugins
builddeps  :
    - pkgconfig(gedit)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(gucharmap-2.90)
    - itstool
    - vala
rundeps    :
    - python3-gobject
setup      : |
    %configure --enable-vala
build      : |
    %make
install    : |
    %make_install
