name       : gedit-plugins
version    : '42.0'
release    : 30
source     :
    - https://download.gnome.org/sources/gedit-plugins/42/gedit-plugins-42.0.tar.xz : 7246420fbc3d3950ef78d2e346e21306440e71c64d74f6e8c44e51a58cd0db62
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Gedit Plugins
description: |
    Gedit Plugins
builddeps  :
    - pkgconfig(gedit)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(gucharmap-2.90)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(vte-2.91)
    - appstream-glib
    - itstool
    - vala
rundeps    :
    - gucharmap
    - libgit2-glib
    - python-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
