name       : gedit-plugins
version    : '40.1'
release    : 27
source     :
    - https://download.gnome.org/sources/gedit-plugins/40/gedit-plugins-40.1.tar.xz : dfb7989507a5745cb17c42fb1472207167a387197354f64254118e4a9437c196
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Gedit Plugins
description: |
    Gedit Plugins
builddeps  :
    - pkgconfig(gedit)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(gucharmap-2.90)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(vte-2.91)
    - appstream-glib
    - itstool
    - vala
rundeps    :
    - libgit2-glib
    - python-gobject
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
