name       : gedit-plugins
version    : 3.28.1
release    : 11
source     :
    - https://download.gnome.org/sources/gedit-plugins/3.28/gedit-plugins-3.28.1.tar.xz : 222dfd7065d399f7eda48dce011b42cc7185cd058f523be1bbd7143980e01468
license    : GPL-2.0
component  : desktop.gnome
summary    : Gedit Plugins
description: |
    Gedit Plugins
builddeps  :
    - pkgconfig(gedit)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(gucharmap-2.90)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(vte-2.91)
    - itstool
    - vala
rundeps    :
    - gitg
    - python3-gobject
setup      : |
    %configure --enable-vala
build      : |
    %make
install    : |
    %make_install
