name       : gedit-plugins
version    : 3.20.0
release    : 5
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gedit-plugins/3.20/gedit-plugins-3.20.0.tar.xz : d4902af5f9f728e0d692ca8c2f7a9f88f6c2ab8c9be037238ffb7d3aebe757bf
license    : GPL-2.0
summary    : Gedit Plugins
description: |
    Gedit Plugins
builddeps  :
    - pkgconfig(gedit)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(gucharmap-2.90)
    - itstool
    - vala
rundeps    :
    - python3-gobject
setup      : |
    %configure --enable-vala
build      : |
    %make
install    : |
    %make_install
