name       : gedit-plugins
version    : 3.22.0
release    : 6
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gedit-plugins/3.22/gedit-plugins-3.22.0.tar.xz : 83a73088de73478841b9a216bd89c2e478aa302b3579a2a8685893d7a6a48fdc
license    : GPL-2.0
component  : desktop.gnome
summary    : Gedit Plugins
description: |
    Gedit Plugins
builddeps  :
    - pkgconfig(gedit)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(gucharmap-2.90)
    - itstool
    - vala
rundeps    :
    - python3-gobject
setup      : |
    %configure --enable-vala
build      : |
    %make
install    : |
    %make_install
